### ISSUE TITLE
Vytvořit discord bota

### ISSUE THREAD

**Issue by vaclavparma** [madebyqwerty/daily-bot#1]
- [x] Naprogramovat bota
- [x] Deplynout bota na server
- [x] Udělat bota konfiguravatelný pomocí config souboru
  - [x] `channel_id` - Určuje do kterého channelu bot posílá zprávu
  - [x] `message` - Zpráva kterou bot pošle
  - [x] `time` - Čas kdy bot zprávu pošle
- [x] Do README napsat instrukce na to jak spustit pro ostatní

**Comment by milan-sedivy** [comment]
Skvělý task, chválím! Jediné co podotknu - protože na tom aktuálně pracuješ tak to hoď do In Progress :) 

Snažte se tento proces automatizovat - pomůže to pak teamleadovi.

**Comment by tomaskebrle** [comment]
Já jsem nějakou automatizaci nastavoval, ale ono je tohle ještě v betě, takže to fuguje tak napůl, tak já se potom ještě na to kouknu.
