### ISSUE TITLE
Zavírání vláken úplně nefunguje

### ISSUE THREAD

**Issue by vaclavparma** [madebyqwerty/daily-bot#7]
Vláno se zavře po pár minutách místo o půlnoci

**Comment by vaclavparma** [comment]
Dal jsem to do "kontroluje se", což nevím, zda je správně, ale už na tom nepracuju - čekám, zda to zítra bude fungovat. Pak kdyžtak udělám další fix/pull request

**Comment by tomaskebrle** [comment]
No řekl bych že když nevíš jestli to funguje a tak čekáš že to vyzkoušíš je spíš Právě se dělá, ale to je jen můj osobní názor. @milan-sedivy @MonteDan co si myslíte vy?

**Comment by milan-sedivy** [comment]
In progress (Prave se dela)
